applications:
- name: tut3-producer
  path: target/rabbit-tutorials-1.7.1.RELEASE.jar
  disk_quota: 1G
  instances: 1
  memory: 1G
  disk_quota: 512M
  random-route: true
  buildpack: java_buildpack
  health-check-type: process
  services:
  - rabbit-mq
  stack: cflinuxfs2
  env:
    CONSUMER: false
    PRODUCER: true
    SPRING_PROFILES_ACTIVE: pub-sub,sender
